apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: kong/charts/kong
    repoURL: https://github.com/claudioed/gateway-poc.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    namespace: kong
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
